apiVersion: rke-machine-config.cattle.io/v1
kind: VmwarevsphereConfig
metadata:
  name: {{ .Values.cluster.name }}-nodes
  namespace: fleet-default
cloneFrom: /Datacenter/vm/ubuntu-jammy-22.04-cloudimg
cloudConfig: |
    #cloud-config

    users:
      - default
      - name: ops
        passwd: "$6$0JSlsuJyJHc/Ofpz$FobP2erNS1Gfpo42cdCXpHJewldt82KyXVg/jnMUw8yquk1eWe4fVaEhhEezcbNychTPzwj.k.AK1IO7sz2bv/"
        lock-passwd: false
        sudo: ALL=(ALL) NOPASSWD:ALL
        groups: users, sudo
        shell: /bin/bash
        ssh-authorized-keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICua5PABqRnTCib17zeyd0Mgusav4mY2KGOmvMzOdfWA Wolfgang Hofbauer <wolfgang.hofbauer@cancom.de>, 2022-06-03

    keyboard:
      layout: de
      
    locale: de_DE

    write_files:
      - path: /root/configure-networking.sh
        content: |
          #!/bin/bash

          vmtoolsd --cmd 'info-get guestinfo.ovfEnv' > /tmp/ovfenv

          # Interface 1
          IPAddress=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.ip.0.address" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
          Gateway=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.route.0.gateway" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
          DNS=$(sed -n 's/.*Property oe:key="guestinfo.dns.servers" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)

          cat > /etc/netplan/01-netcfg.yaml <<EOF
          network:
            version: 2
            renderer: networkd
            ethernets:
              ens192:
                dhcp4: no
                addresses:
                  - ${IPAddress}/24
                routes:
                  - to: default
                    via: $Gateway
                nameservers:
                  addresses: [$DNS]
          EOF
          
          # Hostname
          sudo hostnamectl set-hostname NODE-${IPAddress##*.}

          sudo netplan apply

    runcmd:
      - bash /root/configure-networking.sh
cpuCount: "0"
creationType: template
datacenter: /Datacenter
datastore: /Datacenter/datastore/Profile_004_NFS_DS
diskSize: "0"
folder: /Datacenter/vm/Rancher-Deployment
memorySize: "0"
network:
  - /Datacenter/network/VL-115
  - /Datacenter/network/VL-899
pool: /Datacenter/host/Test-Cluster/Resources/Rancher-Deployment
sshPort: "22"
sshUserGroup: staff
vappIpallocationpolicy: fixedAllocated
vappIpprotocol: IPv4
vappProperty:
  - guestinfo.interface.0.ip.0.address=ip:VL-115
  - guestinfo.interface.0.route.0.gateway=${gateway:VL-115}
  - guestinfo.dns.servers=${dns:VL-115}
  - guestinfo.interface.1.ip.0.address=ip:VL-899
vappTransport: com.vmware.guestInfo
vcenterPort: "443"