apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName }}
  kubernetesVersion: {{ .Values.kubernetesVersion }}
  rkeConfig:
    machinePools:
    - controlPlaneRole: true
      etcdRole: true
      workerRole: false
      quantity: {{ .Values.nodes.quantity }}
      name: {{ .Values.cluster.name }}-nodes
      machineConfigRef:
        kind: VmwarevsphereConfig
        name: {{ .Values.cluster.name }}-nodes
      paused: false
      displayName: {{ .Values.cluster.name }}-nodes
      controlPlaneConfig:
        cni: calico
    - controlPlaneRole: false
      etcdRole: false
      workerRole: true
      quantity: {{ .Values.wnodes.quantity }}
      name: {{ .Values.cluster.name }}-wnodes
      machineConfigRef:
        kind: VmwarevsphereConfig
        name: {{ .Values.cluster.name }}-wnodes
      paused: false
      displayName: {{ .Values.cluster.name }}-nodes
      controlPlaneConfig:
        cni: calico 
